config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get '/' => redirect('/projects')

  resources :projects, param: :slug, only: [:index] do
    resources :suites, param: :slug, only: [:show] do
      resources :runs, param: :sequential_id, only: [:show]
    end
  end

  resources :runs, only: [:new, :create]
  resources :tests, only: [:update, :new, :create]

  get '/baselines/:key', to: 'baselines#show', as: :baseline
end

app/models/suite.rb
class Suite < ActiveRecord::Base
  belongs_to :project
  has_many :runs, dependent: :destroy
  has_many :tests, through: :runs, dependent: :destroy
  has_many :baselines, dependent: :destroy
  after_initialize :create_slug

  def latest_run
    runs.order(id: :desc).first
  end

  def create_slug
    self.slug ||= name.to_s.parameterize
  end

  def to_param
    slug
  end

  def purge_old_runs
    self.runs.order(id: :desc).offset(5).destroy_all
  end
end

app/controllers/suites_controller.rb
class SuitesController < ApplicationController
  def show
    @project = Project.find_by_slug!(params[:project_slug])
    @suite = @project.suites.find_by_slug!(params[:slug])

    @baselines = TestFilters.new(@suite.baselines, params)
  end
end

app/helpers/suites_helper.rb
module SuitesHelper
end

app/views/suites/show.html.erb
<%
@page_title = "#{@suite.name} (#{@suite.project.name})"
%>

<ul class="breadcrumb">
  <li><%= link_to 'Projects', projects_url %></li>
  <li><%= link_to @suite.project.name, projects_url %></li>
  <li><%= @suite.name %></li>
</ul>

<h1><%= @suite.name %> <span class="text-muted">(<%= @suite.project.name %>)</span></h1>

<h2>Latest runs</h2>
<table>
  <thead>
    <tr>
      <th>Run</th>
      <th>Date</th>
      <th>Result</th>
    </tr>
  </thead>
  <tbody>
    <% @suite.runs.reversed.limit(5).each do |run| %>
      <tr>
        <th><%= link_to "##{run.sequential_id}", project_suite_run_path(run.suite.project, run.suite, run) %></th>
        <td class="text-muted"><%= format_date(run.created_at) %></td>
        <td>
          <% if run.tests.count == 0 %>
            <span class="label label-info">No tests</span>
          <% end %>
          <% if run.passing_tests > 0 %>
            <a class="label label--pass" href="<%= project_suite_run_path(run.suite.project, run.suite, run, params: { status: 'pass' }) %>"><%= run.passing_tests %> passed</a>
          <% end %>
          <% if run.failing_tests > 0 %>
            <a class="label label--fail" href="<%= project_suite_run_path(run.suite.project, run.suite, run, params: { status: 'fail' }) %>"><%= run.failing_tests %> failed</a>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Baselines</h2>
<%= render 'shared/test_filters', test_filters: @baselines %>
<table>
  <thead>
    <tr>
      <th>Test name</th>
      <th>Browser</th>
      <th>Size</th>
      <th>Screenshot</th>
    </tr>
  </thead>
  <tbody>
    <% @baselines.tests.each do |baseline| %>
      <tr class="baseline">
        <th><%= link_to(baseline.name, baseline.screenshot_url, class: 'baseline__name') %></th>
        <td><%= baseline.browser %></td>
        <td><%= baseline.size %></td>
        <td><%= link_to(thumbnail(baseline.screenshot_thumbnail), baseline.screenshot_url, class: 'baseline__image') %></td>
      </tr>
    <% end %>
  </tbody>
</table>