config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get '/' => redirect('/projects')

  resources :projects, param: :slug, only: [:index] do
    resources :suites, param: :slug, only: [:show] do
      resources :runs, param: :sequential_id, only: [:show]
    end
  end

  resources :runs, only: [:new, :create]
  resources :tests, only: [:update, :new, :create]

  get '/baselines/:key', to: 'baselines#show', as: :baseline
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :suites, :dependent => :destroy
  after_initialize :create_slug

  def create_slug
    self.slug ||= name.to_s.parameterize
  end

  def to_param
    slug
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.html.erb
<%
@page_title = 'Projects'
%>

<h1>Projects</h1>

<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>Name</th>
      <th>Suite</th>
      <th>Last run</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.includes(:suites).each do |project| %>
      <% project.suites.each_with_index do |suite, i| %>
      <tr id="project_<%= project.id %>" class="project">
        <th><%= project.name %></th>
        <td><%= link_to suite.name, project_suite_path(suite.project, suite) %></td>
        <td><%= link_to "##{suite.latest_run.sequential_id}", project_suite_run_path(suite.project, suite, suite.latest_run) %> <span class="text-muted"><%= format_date(suite.latest_run.created_at) %></span>
          <% if suite.latest_run.tests.count == 0 %>
            <span class="label label-info">No tests</span>
          <% end %>
          <% if suite.latest_run.passing_tests > 0 %>
            <a class="label label--pass" href="<%= project_suite_run_path(suite.project, suite, suite.latest_run, params: { status: 'pass' }) %>"><%= suite.latest_run.passing_tests %> passed</a>
          <% end %>
          <% if suite.latest_run.failing_tests > 0 %>
            <a class="label label--fail" href="<%= project_suite_run_path(suite.project, suite, suite.latest_run, params: { status: 'fail' }) %>"><%= suite.latest_run.failing_tests %> failed</a>
          <% end %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>