config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get '/' => redirect('/projects')

  resources :projects, param: :slug, only: [:index] do
    resources :suites, param: :slug, only: [:show] do
      resources :runs, param: :sequential_id, only: [:show]
    end
  end

  resources :runs, only: [:new, :create]
  resources :tests, only: [:update, :new, :create]

  get '/baselines/:key', to: 'baselines#show', as: :baseline
end

app/models/run.rb
class Run < ActiveRecord::Base
  after_create :purge_old_runs
  belongs_to :suite
  has_many :tests, dependent: :destroy
  acts_as_sequenced scope: :suite_id

  def self.reversed
    order('created_at DESC')
  end

  def to_param
    sequential_id.to_s
  end

  def as_json(options)
    run = super(options)
    run[:url] = self.url
    return run
  end

  def passing_tests
    self.tests.where(pass: true).count
  end

  def failing_tests
    self.tests.where(pass: false).count
  end

  def url
    Rails.application.routes.url_helpers.project_suite_run_path(self.suite.project, self.suite, self)
  end

  private

  def purge_old_runs
    self.suite.purge_old_runs
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def show
    project = Project.find_by_slug!(params[:project_slug])
    suite = project.suites.find_by_slug!(params[:suite_slug])
    @run = suite.runs.find_by_sequential_id!(params[:sequential_id])
    @test_filters = TestFilters.new(@run.tests, true, params)

    respond_to do |format|
      format.html
      format.json {
        render json: @run.to_json(:include => :tests)
      }
    end
  end

  def new
    @run = Run.new
  end

  def create
    project = Project.find_or_create_by(name: params[:project])
    suite = project.suites.find_or_create_by(name: params[:suite])
    @run = suite.runs.create
    render :json => @run.to_json
  end
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/runs/new.html.erb
<form method="post" action="<%= runs_url %>">
  <input type="text" name="project" placeholder="Project">
  <input type="text" name="suite" placeholder="Suite">
  <input type="submit" value="Create run">
</form>

app/views/runs/show.html.erb
<%
@page_title = "#{@run.suite.name} ##{@run.sequential_id} (#{@run.suite.project.name})"
%>

<ul class="breadcrumb">
  <li><%= link_to 'Projects', projects_url %></li>
  <li><%= link_to @run.suite.project.name, projects_url %></li>
  <li><%= link_to @run.suite.name, project_suite_url(@run.suite.project, @run.suite) %></li>
  <li>#<%= @run.sequential_id %></li>
</ul>

<h1>Run #<%= @run.sequential_id %> <span class="text-muted">(<%= @run.suite.name %>)</span></h1>

<%= render 'shared/test_filters', test_filters: @test_filters %>

<table class="table table-striped ">
  <thead class="thead-inverse">
    <tr>
      <th>Test name</th>
      <th>Baseline</th>
      <th>Comparison</th>
      <th>Diff</th>
      <th>Result</th>
    </tr>
  </thead>
  <tbody>
    <% @test_filters.tests.each do |test| %>
      <%= render test %>
    <% end %>
    <% if @test_filters.tests.count == 0 %>
    <tr>
      <td colspan="5">No matching tests found.</td>
    </tr>
    <% end %>
  </tbody>
</table>